# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'Recharge'
version: '1.0.0'
config-version: 2

require-dbt-version: [">=1.0.0", "<2.0.0"]

profile: 'edm_data_transformation'

vars:
  raw_database: "edm-saras" #equivalent to project_id in BigQuery
  raw_schema: "EDM_Daton" #equivalent to dataset in BigQuery
  currency_conversion_flag: False
  get_brandname_from_tablename_flag: True
  brandname_position_in_tablename: 0
  # Example- default_brandname: "Nike"
  default_brandname: "" 
  get_storename_from_tablename_flag: True 
  storename_position_in_tablename: 1
  # Example- default_storename: "US"
  default_storename: "" 

  timezone_conversion_flag : True
  to_timezone: 'Europe/Dublin' # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

  RechargeCharges : True
  RechargeCustomers : True
  RechargeDiscounts : True
  RechargeOnetimes : True
  RechargeAddress : True
  RechargeProducts : True
  RechargeCollections : True
  RechargeOrderLineItems : True
  RechargeOrderLineItemsProperties : True
  RechargeSubscriptions : True


  recharge_address_tbl_ptrn: '%recharge%address'
  recharge_address_tbl_exclude_ptrn: ''
  recharge_address_lookback: 172800000

  recharge_charges_tbl_ptrn: '%recharge%charges'
  recharge_charges_tbl_exclude_ptrn: ''
  recharge_charges_lookback: 172800000
  
  recharge_customers_tbl_ptrn: '%recharge%customers'
  recharge_customers_tbl_exclude_ptrn: ''
  recharge_customers_lookback: 172800000

  recharge_discounts_tbl_ptrn: '%recharge%discounts'
  recharge_discounts_tbl_exclude_ptrn: ''
  recharge_discounts_lookback: 172800000

  recharge_onetimes_tbl_ptrn: '%recharge%onetimes'
  recharge_onetimes_tbl_exclude_ptrn: ''
  recharge_onetimes_lookback: 172800000

  recharge_orderslineitems_tbl_ptrn: '%recharge%orderslineitems'
  recharge_orderslineitems_tbl_exclude_ptrn: ''
  recharge_orderslineitems_lookback: 172800000


  recharge_charges_tbl_ptrn: '%recharge%charges'
  recharge_charges_tbl_exclude_ptrn: ''
  recharge_charges_lookback: 172800000
  
  recharge_customers_tbl_ptrn: '%recharge%customers'
  recharge_customers_tbl_exclude_ptrn: ''
  recharge_customers_lookback: 172800000

  recharge_discounts_tbl_ptrn: '%recharge%discounts'
  recharge_discounts_tbl_exclude_ptrn: ''
  recharge_discounts_lookback: 172800000

  recharge_onetimes_tbl_ptrn: '%recharge%onetimes'
  recharge_onetimes_tbl_exclude_ptrn: ''
  recharge_onetimes_lookback: 172800000

  recharge_orderslineitems_tbl_ptrn: '%recharge%orders'
  recharge_orderslineitems_tbl_exclude_ptrn: ''
  recharge_orderslineitems_lookback: 172800000
  
  recharge_orderslineitemsproperties_tbl_ptrn: '%recharge%orders'
  recharge_orderslineitemsproperties_tbl_exclude_ptrn: ''
  recharge_orderslineitemsproperties_lookback: 172800000

  recharge_subscriptions_tbl_ptrn: '%recharge%subscriptions'
  recharge_subscriptions_tbl_exclude_ptrn: ''
  recharge_subscriptions_lookback: 172800000
  
  recharge_products_tbl_ptrn: '%recharge%products'
  recharge_products_tbl_exclude_ptrn: ''
  recharge_products_lookback: 172800000

  recharge_collections_tbl_ptrn: '%recharge%collections'
  recharge_collections_tbl_exclude_ptrn: ''
  recharge_collections_lookback: 172800000





  
# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:    
  Recharge:
    +schema: stg_recharge


