# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'Recharge'
version: '1.0.0'
config-version: 2

require-dbt-version: [">=1.0.0", "<2.0.0"]

profile: 'edm_data_transformation'

vars:
  raw_database: "edm-saras" #equivalent to project_id in BigQuery
  raw_schema: "EDM_Daton" #equivalent to dataset in BigQuery
  currency_conversion_flag: False
  get_brandname_from_tablename_flag: True
  brandname_position_in_tablename: 0
  # Example- default_brandname: "Nike"
  default_brandname: "" 
  get_storename_from_tablename_flag: True 
  storename_position_in_tablename: 1
  # Example- default_storename: "US"
  default_storename: "" 

  RechargeCharges : True
  RechargeCustomers : True
  RechargeDiscounts : True
  RechargeOnetimes : True
  RechargeAddress : True
  RechargeProducts : True
  RechargeCollections : True
  RechargeOrderLineItems : True
  RechargeOrderLineItemsProperties : True
  RechargeSubscriptions : True

  recharge_address_tbl_ptrn: '%recharge_bq_address'
  recharge_address_tbl_exclude_ptrn: ''
  recharge_address_lookback: 2592000000

  recharge_charges_tbl_ptrn: '%recharge_bq_charges'
  recharge_charges_tbl_exclude_ptrn: ''
  recharge_charges_lookback: 2592000000
  
  recharge_customers_tbl_ptrn: '%recharge_bq_customers'
  recharge_customers_tbl_exclude_ptrn: ''
  recharge_customers_lookback: 2592000000

  recharge_discounts_tbl_ptrn: '%recharge_bq_discounts'
  recharge_discounts_tbl_exclude_ptrn: ''
  recharge_discounts_lookback: 2592000000

  recharge_onetimes_tbl_ptrn: '%recharge_bq_onetimes'
  recharge_onetimes_tbl_exclude_ptrn: ''
  recharge_onetimes_lookback: 2592000000

  recharge_orderslineitems_tbl_ptrn: '%recharge_bq_orderslineitems'
  recharge_orderslineitems_tbl_exclude_ptrn: ''
  recharge_orderslineitems_lookback: 2592000000
  recharge_address_tbl_ptrn: '%recharge_bq_address'
  recharge_address_tbl_exclude_ptrn: ''
  recharge_address_lookback: 2592000000

  recharge_charges_tbl_ptrn: '%recharge_bq_charges'
  recharge_charges_tbl_exclude_ptrn: ''
  recharge_charges_lookback: 2592000000
  
  recharge_customers_tbl_ptrn: '%recharge_bq_customers'
  recharge_customers_tbl_exclude_ptrn: ''
  recharge_customers_lookback: 2592000000

  recharge_discounts_tbl_ptrn: '%recharge_bq_discounts'
  recharge_discounts_tbl_exclude_ptrn: ''
  recharge_discounts_lookback: 2592000000

  recharge_onetimes_tbl_ptrn: '%recharge_bq_onetimes'
  recharge_onetimes_tbl_exclude_ptrn: ''
  recharge_onetimes_lookback: 2592000000

  recharge_orderslineitems_tbl_ptrn: '%recharge_bq_orders'
  recharge_orderslineitems_tbl_exclude_ptrn: ''
  recharge_orderslineitems_lookback: 2592000000
  
  recharge_orderslineitemsproperties_tbl_ptrn: '%recharge_bq_orders'
  recharge_orderslineitemsproperties_tbl_exclude_ptrn: ''
  recharge_orderslineitemsproperties_lookback: 2592000000

  recharge_subscriptions_tbl_ptrn: '%recharge_bq_subscriptions'
  recharge_subscriptions_tbl_exclude_ptrn: ''
  recharge_subscriptions_lookback: 2592000000
  
  recharge_products_tbl_ptrn: '%recharge_bq_products'
  recharge_products_tbl_exclude_ptrn: ''
  recharge_products_lookback: 2592000000

  recharge_collections_tbl_ptrn: '%recharge_bq_collections'
  recharge_collections_tbl_exclude_ptrn: ''
  recharge_collections_lookback: 2592000000


  timezone_conversion_flag : False
  raw_table_timezone_offset_hours: {
    "edm-saras.EDM_Daton.Brand_US_Recharge_BQ_Charges" : -7,
    "edm-saras.EDM_Daton.Brand_US_Recharge_BQ_Customers" : -7,
    "edm-saras.EDM_Daton.Brand_US_Recharge_BQ_Discounts" : -7,
    "edm-saras.EDM_Daton.Brand_US_Recharge_BQ_Onetimes" : -7,
    "edm-saras.EDM_Daton.Brand_US_Recharge_BQ_Address" : -7,
    "edm-saras.EDM_Daton.Brand_US_Recharge_BQ_Products" : -7,
    "edm-saras.EDM_Daton.Brand_US_Recharge_BQ_Collections" : -7,
    "edm-saras.EDM_Daton.Brand_US_Recharge_BQ_Orders" : -7,
    "edm-saras.EDM_Daton.Brand_US_Recharge_BQ_Subscriptions" : -7
    }

  
# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:    
  Recharge:
    +schema: stg_recharge


